# Generated by Django 6.0.6 on 2026-06-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan_waiting_since', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('chatter', models.ForeignKey(limit_choices_to={'role': 'chatter'}, on_delete=django.db.models.deletion.CASCADE, related_name='chatter_dialogs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(limit_choices_to={'role': 'model'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_dialogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dialog',
                'verbose_name_plural': 'Dialogs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('fan', 'Fan'), ('chatter', 'Chatter')], max_length=10)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('ppv', 'PPV')], default='text', max_length=10)),
                ('ppv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.dialog')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
